import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { FilterProvider } from '@/Providers/FiltersProvider';

const SFPro = localFont({
  src: '../fonts/SF-Pro-Regular.otf',
  display: 'swap',
  variable: '--SF-pro',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${SFPro.variable}`}>
        <FilterProvider>{children}</FilterProvider>
      </body>
    </html>
  );
}
